swagger: '2.0'
info:
  title: Example yaml.spec
  description: |
    <h1>hello <img src=x> <iframe src="http://testphp.vulnweb.com">
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
